import '@/styles/globals.css';

export const metadata = {
  title: 'NFT Listing Page',
  description: 'NFT Listing Page Generated by Next.js',
};
// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
